name: Pipeline
on:
    push:
        branches:
            - main
            - gh-actions
    pull_request:
        branches:
            - main
            - gh-actions

jobs:
    run-automated-tests:
        runs-on: ubuntu-latest        
        steps:
            - name: Checkout code / Fetch code
              uses: actions/checkout@v4

            - name: Setup Node.js version
              uses: actions/setuo-node@v4
              with:
                node-version: '20'

            - name: Install node packages
              run: npm install

            - name: Restore database
              run: cat db_BACKUP.json > db.json
              
              
            - name: Start Application
              run: npm run server

            - name: Run Tests
              run: npm run run-tests
              
            - name: Save test run artifacts
              uses: actions/upload-artifact@v4
              with:
                name: playwright-test-results
                path: ./playwright-report
                if-no-files-found: warn
                include-hidden-files: fa